### ISSUE TITLE
No ATF metric in output

### ISSUE THREAD

**Issue by e-orlov** [TeamRossi/ATF-chrome-plugin#3]
My output looks like
```
DOM:      3968.00
II_plt:   4026.97
II_atf:   4026.97
OI_plt:   4497.72
OI_atf:   4536.34
BI_plt:   4026.97
BI_atf:   4026.97
ATF_img:  4003.10
JS:       6286.10
CSS:      7290.80
PLT:      6955.00
```
There is no ATF metric, as shown on your screenshot, just ImageIndex, ObjectIndex and ByteIndex..

**Comment by diegohora** [comment]
Well, the ATF approximation should be shown right bellow PLT. Is this problem consistently happening?

**Comment by e-orlov** [comment]
I thought so too:( but isn' there... 
yes, it is missed on all tested pages, from different domains.
I'm running the plugin from Chrome webstore.

Now i'm a bit further... Deinstalled extension from webstore, and installed the one from here, from GitHub, in devmode. Now ATF is in the place... But - weird thing: in many cases ATF is longer than PLT

**Comment by nonsns** [comment]
Well, I zuspect Diego just renamed it to ATF_img, confirm?

All other integral metrics are there...

Best
D.

**Comment by diegohora** [comment]
I will soon update chrome-store version to reflect latest git-hub version. 

* ATF longer than PLT sometimes can happen: this is because the page continues to fetch content after onload triggers. We are in the process of better defining heuristics to distinguish between non-visual events (e.g. AJAX calls, request of non visible images) and visible events (e.g. banners, carroussel elements). You can minimize this by reducing the delay between onload and plugin execution on options page. 

I'm closing this issue.
